- name: Configure Web server
  hosts: server_role_web
  remote_user: debian       
  become: true
  roles:
    - frontend

- name: Configure Database server
  hosts: server_role_database
  remote_user: rocky         
  become: true
  roles:
    - frontend
