- name: Configure Web server
  hosts: server_role_web
  remote_user: admin      
  become: true

- name: Configure Database server
  hosts: server_role_database
  remote_user: rocky         
  become: true

